# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=15)),
                ('sports', models.CommaSeparatedIntegerField(max_length=20)),
                ('moviesTV', models.CommaSeparatedIntegerField(max_length=20)),
                ('dancePA', models.CommaSeparatedIntegerField(max_length=20)),
                ('lit', models.CommaSeparatedIntegerField(max_length=20)),
                ('travel', models.BooleanField(default=False)),
                ('gaming', models.CommaSeparatedIntegerField(max_length=20)),
                ('pfa', models.CommaSeparatedIntegerField(max_length=20)),
                ('cooking', models.BooleanField(default=False)),
                ('collection', models.BooleanField(default=False)),
                ('music', models.CommaSeparatedIntegerField(max_length=20)),
            ],
        ),
    ]
